import { page } from "./page";

export const SUBJECT_OF_STUDY = "Computer Science (Software Engineering)";
export const STUDYING_UNTIL = new Date("2027-07-01T00:00:00Z");
export const WEBSOCKET_URL = "wss://api.lanyard.rest/socket";
export const YEAR_STARTED_PROGRAMMING_PROFESSIONALLY = 2023;
export const AVATAR = "Secondary_Dark_Short_Sig_Avatar";
export const MUSIC_STREAMING_PLATFORM = "YouTube Music";
export const SWITCH_FRIEND_CODE = "SW-8471-1596-9212";
export const PROFESSION = "Aspiring Network Engineer";
export const CDN = "https://cdn.notnick.io/images";
export const BLOGS_DIR = `posts${page.blog.path}`;
export const NOTES_DIR = `posts${page.note.path}`;
export const DISCORD_ID = "463449066672619520";
export const SECONDARY_THEME_COLOR = "#25A244";
export const EMAIL_ADDRESS = "hi@notnick.io";
export const YEAR_STARTED_PROGRAMMING = 2019;
export const AVATAR_FILE_EXTENSION = "png";
export const FULL_NAME = "Nicholas Njoki";
export const LONG_POST_LINE_COUNT = 1000;
export const LOCATED = "United Kingdom";
export const FIRST_NAME = "Nicholas";
export const DOMAIN = "notnick.io";
export const CITY = "Canterbury";
export const PRONOUNS = "he/him";
export const THEME = "#30D158";
export const MAIN_CONTENT_ID = "main-content";
