import { generateRandomId } from "./generate-random-id";
import { Experience } from "./../types/experience";
import { page } from "./page";

export const EXPERIENCE: Experience[] = [
  {
    id: generateRandomId(),
    name: "Aviato",
    description: "React Engineer",
    year: 2023,
    logo: `${page.experience.path}/logo/Aviato.jpg`,
    employmentType: "contract",
    location: "Carmel, Indiana - United States",
    remote: true,
    current: false,
    link: "https://www.joinaviato.com/",
    task: "Helped out with building, maintaining, implementing, and improving the user experience on Aviato.",
    filter: "Engineering",
    showCurrentStatus: true,
    slug: "aviato",
    discontinued: false,
    feature: true,
  },
  {
    id: generateRandomId(),
    name: "Drop Zone",
    description: "Manager",
    year: 2019,
    logo: `${page.experience.path}/logo/DropZone.jpeg`,
    employmentType: "part-time",
    location: "United States, America",
    remote: true,
    current: false,
    link: "https://www.youtube.com/channel/UCYFjrIHMnYmQRm1IGMS9pAw",
    task: "Helped up with uploads on the channel, and social media, and managed the Drop Zone community.",
    filter: "YouTube",
    showCurrentStatus: true,
    slug: "drop-zone",
    discontinued: true,
    feature: true,
  },
  {
    id: generateRandomId(),
    name: "Aquila",
    description: "Channel Manager",
    year: 2023,
    logo: `${page.experience.path}/logo/Aquila.jpeg`,
    employmentType: "part-time",
    location: "England, United Kingdom",
    remote: true,
    current: true,
    link: "https://www.youtube.com/@aquila",
    task: "Primary focus is to provide daily uploads.",
    filter: "YouTube",
    showCurrentStatus: true,
    slug: "aquila",
    discontinued: false,
    feature: true,
  },
  {
    id: generateRandomId(),
    name: "Chill Zone",
    description: "Channel Manager",
    year: 2019,
    logo: `${page.experience.path}/logo/ChillZone.jpg`,
    employmentType: "voluntary",
    location: "United States, America",
    remote: true,
    current: false,
    link: "https://www.youtube.com/results?search_query=chill+zone+lyrics",
    task: "A music channel I helped manage.",
    filter: "YouTube",
    showCurrentStatus: true,
    slug: "chill-zone",
    discontinued: false,
    feature: true,
  },
  {
    id: generateRandomId(),
    name: "Watchou",
    description: "Frontend Engineer",
    year: 2021,
    logo: `${page.experience.path}/logo/Watchou.jpeg`,
    employmentType: "voluntary",
    location: "Mississauga, Ontario - Canada",
    remote: true,
    current: false,
    link: "https://watchou.com/",
    task: "One primary task was to convert the React app to from consuming a RESTful API to a GraphQL API.",
    filter: "Engineering",
    showCurrentStatus: true,
    slug: "watchou",
    discontinued: true,
    feature: true,
  },
  {
    id: generateRandomId(),
    name: "SavourTunes",
    description: "Channel Founder",
    year: 2019,
    logo: `${page.experience.path}/logo/SavourTunes.png`,
    employmentType: "part-time",
    location: "England, United Kingdom",
    remote: true,
    current: false,
    link: "https://www.youtube.com/@savourtunes",
    task: "A lyrical music channel I founded in 2019. I had to discontinue the project since it was nearly impossible to monetize or get the channel into a MCN (Multi-Channel Network).",
    filter: "YouTube",
    showCurrentStatus: true,
    slug: "savourtunes",
    discontinued: true,
    feature: false,
  },
];
