import { generateRandomId } from "./generate-random-id";
import { Experience } from "./../types/experience";
import { page } from "./page";

export const EXPERIENCE: Experience[] = [
  {
    id: generateRandomId(),
    name: "Aviato",
    description: "Software Engineer",
    startYear: 2023,
    endYear: 2023,
    startMonth: "jan",
    endMonth: "jul",
    logo: `${page.experience.path}/logo/Aviato.jpg`,
    employmentType: "internship",
    location: "Carmel, Indiana - United States",
    remote: true,
    current: false,
    link: "https://www.joinaviato.com/",
    task: "Helped out with building, maintaining, implementing, and improving the user experience on Aviato.",
    filter: "Engineering",
    showCurrentStatus: true,
    slug: "aviato",
    discontinued: false,
    feature: true,
  },
  {
    id: generateRandomId(),
    name: "Lyrics Tags Generator",
    description: "Software Engineer",
    startYear: 2025,
    startMonth: "jan",
    endYear: 2026,
    endMonth: "jan",
    logo: `${page.experience.path}/logo/LyricsTagsGenerator.png`,
    employmentType: "self-employed",
    location: "England, United Kingdom",
    remote: true,
    current: false,
    link: "https://tags.notnick.io/",
    task: "Built an API/Service for promotional music channels to generate relevant metadata for their YouTube videos.",
    filter: "Project",
    showCurrentStatus: true,
    slug: "lyricstagsgenerator",
    discontinued: false,
    feature: true,
  },
  {
    id: generateRandomId(),
    name: "Watchou",
    description: "Software Engineer",
    startYear: 2021,
    endYear: 2021,
    startMonth: "sep",
    endMonth: "nov",
    logo: `${page.experience.path}/logo/Watchou.jpeg`,
    employmentType: "voluntary",
    location: "Mississauga, Ontario - Canada",
    remote: true,
    current: false,
    link: "https://watchou.com/",
    task: "One of the main contributions was migrating the frontend to consume the GraphQL API and improving data-fetching efficiency.",
    filter: "Engineering",
    showCurrentStatus: true,
    slug: "watchou",
    discontinued: true,
    feature: true,
  },
  {
    id: generateRandomId(),
    name: "Bright Network",
    description: "Participant",
    startYear: 2026,
    endYear: 2026,
    startMonth: "may",
    endMonth: "jun",
    logo: `${page.experience.path}/logo/BrightNetwork.jpg`,
    employmentType: "virtual-internship",
    location: "England, United Kingdom",
    remote: true,
    current: false,
    link: "https://www.brightnetwork.co.uk/",
    task: "Attended Bright Network's IEUK 2026: Technology & Engineering, a four-day virtual internship of skill-building sessions and an employer-set Sector Skills Project.",
    filter: "Engineering",
    showCurrentStatus: true,
    slug: "bright-network",
    discontinued: false,
    feature: true,
  },
  {
    id: generateRandomId(),
    name: "Aquila [earlyentry.io]",
    description: "Channel Manager",
    startYear: 2023,
    endYear: 2024,
    startMonth: "dec",
    endMonth: "dec",
    logo: `${page.experience.path}/logo/Aquila.jpeg`,
    employmentType: "part-time",
    location: "England, United Kingdom",
    remote: true,
    current: false,
    link: "https://www.youtube.com/@aquila",
    task: "Focused on uploading and scheduling content to keep the channel active and consistent.",
    filter: "YouTube",
    showCurrentStatus: true,
    slug: "aquila",
    discontinued: false,
    feature: true,
  },
  {
    id: generateRandomId(),
    name: "Drop Zone",
    description: "Channel Manager",
    startYear: 2019,
    endYear: 2020,
    startMonth: "jan",
    endMonth: "jan",
    logo: `${page.experience.path}/logo/DropZone.jpeg`,
    employmentType: "voluntary",
    location: "United States, America",
    remote: true,
    current: false,
    link: "https://www.youtube.com/channel/UCYFjrIHMnYmQRm1IGMS9pAw",
    task: "Handled video uploads and the channel's social media presence, while growing and moderating the Drop Zone Discord community.",
    filter: "YouTube",
    showCurrentStatus: true,
    slug: "drop-zone",
    discontinued: true,
    feature: true,
  },
  // {
  //   id: generateRandomId(),
  //   name: "SavourTunes",
  //   description: "Founder & Content Manager",
  //   year: 2022,
  //   logo: `${page.experience.path}/logo/SavourTunes.png`,
  //   employmentType: "part-time",
  //   location: "England, United Kingdom",
  //   remote: true,
  //   current: false,
  //   link: "https://www.youtube.com/@savourtunes",
  //   task: "A lyrical promotional music channel that performed quite well in the algorithm when it was active.",
  //   filter: "YouTube",
  //   showCurrentStatus: true,
  //   slug: "drop-zone",
  //   discontinued: true,
  //   feature: true,
  // },
  // {
  //   id: generateRandomId(),
  //   name: "Polaris Lyrics [earlyentry.io]",
  //   description: "Content Manager",
  //   year: 2024,
  //   logo: `${page.experience.path}/logo/PolarisLyrics.jpg`,
  //   employmentType: "part-time",
  //   location: "England, United Kingdom",
  //   remote: true,
  //   current: true,
  //   link: "https://www.youtube.com/@polaristracks",
  //   task: "Focused on delivering content to the channel.",
  //   filter: "YouTube",
  //   showCurrentStatus: true,
  //   slug: "polarislyrics",
  //   discontinued: false,
  //   feature: true,
  // },
];
