export const page = {
  home: {
    name: "/",
    path: "/",
    link: "/",
  },
  blog: {
    title: "Blog",
    name: "blog",
    path: "/blog",
    link: "/blog",
  },
  note: {
    title: "Note",
    name: "note",
    path: "/note",
    link: "/note",
  },
  talks: {
    title: "Talks",
    name: "talks",
    path: "/talks",
    link: "/talks",
  },
  isrc: {
    title1: "ISRC Finder",
    title2: "ISRC",
    path: "/isrc",
    link: "/isrc",
    name: "isrc",
  },
  branding: {
    title: "Branding",
    path: "/branding",
    link: "/branding",
    name: "branding",
  },
  projects: {
    title: "Projects",
    path: "/projects",
    link: "/projects",
    name: "/projects",
  },
  paths: {
    title: "Paths",
    path: "/paths",
    link: "/paths",
    name: "paths",
  },
  components: {
    title: "Components",
    path: "/components",
    link: "/components",
    name: "components",
  },
  experience: {
    title: "Experience",
    path: "/experience",
    link: "/experience",
    name: "path",
  },
  license: {
    title: "License",
    path: "/license",
    link: "/license",
    name: "license",
  },
  switch: {
    games: {
      title: "Nintendo Switch Games",
      path: "/switch/games",
      link: "/switch/games",
      name: "games",
    },
    path: "/switch",
    link: "/switch",
    name: "switch",
  },
  quote: {
    title: "Quote",
    path: "/quote",
    link: "/quote",
    name: "quote",
  },
  socials: {
    title: "Socials",
    path: "/socials",
    link: "/socials",
  },
  specs: {
    title: "Specs",
    specs: "specs",
    path: "/specs",
    link: "/specs",
  },
  articles: {
    title: "Articles",
    path: "/articles",
    link: "/articles",
  },
  credit: {
    credit: "credit",
    title: "Credit",
    path: "/credit",
    link: "/credit",
  },
  feedback: {
    lyricsTagsGenerator: {
      name: "Lyrics Tags Generator",
      title: "Feedback",
    },
  },
  challenge: {
    title: "Challenge",
    path: "/challenge",
    link: "/challenge",
    name: "challenge",
  },
  community: {
    title2: "Community Rules",
    title1: "Community",
    name: "community",
    rules: {
      path: "/community/rules",
      link: "/community/rules",
      name: "rules",
    },
  },
  contributors: {
    title: "Contributors",
    path: "/contributors",
    link: "/contributors",
    name: "contributors",
  },
  music: {
    title: "Music",
    path: "/music",
    link: "/music",
    name: "music",
  },
  rags: {
    title: "Rags",
    path: "/rags",
    link: "/rags",
    name: "rags",
  },
  dev: {
    title: "Dev",
    path: "/dev",
    link: "/dev",
    name: "dev",
  },
};
