import { generateRandomId } from "./generate-random-id";
import { Project } from "../types/project";

export const PROJECTS: Project[] = [
  {
    logo: "/project/branding/lyrics-tags-generator.png",
    name: "Lyrics Tags Generator",
    id: generateRandomId(),
    site: "tags.notnick.io",
    kind: "website",
    active: true,
    oss: false,
    desc: "Generate YouTube tags for your lyric videos.",
  },
  {
    logo: "/project/branding/notnick-io.png",
    name: "My Personal Website",
    id: generateRandomId(),
    site: "notnick.io",
    kind: "website",
    active: true,
    oss: true,
    desc: "You're currently on it right now! This is my personal site.",
  },
  {
    logo: "/project/branding/mgc.png",
    name: "Module Grade Calculator",
    id: generateRandomId(),
    site: "",
    link: "https://github.com/Nicholas-FnF/module-grade-calculator",
    github: "https://github.com/Nicholas-FnF/module-grade-calculator",
    kind: "website",
    active: true,
    oss: true,
    desc: "A small program to calculate module grades.",
  },
  {
    logo: "/project/branding/vercel-swag-logo.jpg",
    name: "Vercel Swag",
    id: generateRandomId(),
    site: "vercel-swag.vercel.app",
    kind: "website",
    active: true,
    oss: true,
    desc: "A gallery collection site of vercel merchandise.",
  },
  {
    logo: "/project/branding/notnick-io.png",
    name: "My Personal Gallery",
    id: generateRandomId(),
    site: "pics.notnick.io",
    kind: "website",
    link: "https://pics.notnick.io/",
    github: "https://github.com/alsonick/pics.notnick.io",
    active: true,
    oss: true,
    desc: "Think of it as my own Instagram website.",
  },
  {
    logo: "",
    name: "Lyrics Tags Generator Bot",
    id: generateRandomId(),
    site: "tags.notnick.io",
    kind: "website",
    link: "https://discord.com/oauth2/authorize?client_id=1338567480834265193&permissions=2147534848&integration_type=0&scope=bot",
    active: true,
    oss: false,
    desc: "Discord bot version of Lyrics Tags Generator.",
  },
];
