export const PROJECTS = [
  {
    id: 1,
    name: "notnick.io",
    desc: "The source code to my personal site, written with Next.js, Prisma, Tailwindcss & TypeScript, hosted and deployed on Vercel.",
    active: true,
    github: "https://github.com/alsonick/notnick.io",
    oss: true,
    site: "https://notnick.io/",
  },
  {
    id: 2,
    name: "Aviato",
    desc: "A platform the allows you to pitch to funds directly anywhere, anytime.",
    active: true,
    github: "",
    oss: false,
    site: "https://www.joinaviato.com/",
  },
  {
    id: 2,
    name: "blog-tags-generator",
    desc: "A small tool I made during a lecture today that quickly generates unique tags for your blog pages.",
    active: true,
    github: "https://github.com/alsonick/blog-tags-generator",
    oss: true,
    site: "https://blog-tags-generator.vercel.app/",
  },

  {
    id: 3,
    name: "pics",
    desc: "A website to hold a collection of cool pictures I've taken, written in Next.js, Tailwindcss & TypeScript, hosted and deployed on Vercel.",
    active: true,
    github: "https://github.com/alsonick/pics",
    oss: true,
    site: "https://pics.notnick.io/",
  },
  {
    id: 4,
    name: "chat-gpt-cli",
    desc: "Tiny cli tool that allows you to interact with ChatGPT.",
    active: false,
    github: "https://github.com/alsonick/chat-gpt-cli",
    oss: true,
    site: "",
  },
];
