import { generateRandomId } from "./generate-random-id";
import { Project } from "../types/project";

export const PROJECTS: Project[] = [
  {
    logo: "/project/branding/lyrics-tags-generator.png",
    name: "Lyrics Tags Generator",
    id: generateRandomId(),
    site: "tags.notnick.io",
    kind: "website",
    link: "https://tags.notnick.io/",
    github: "https://github.com/alsonick/tags.notnick.io",
    active: true,
    oss: true,
    desc: "A YouTube utility metadata generator service.",
  },
  {
    logo: "/project/branding/daily-walks.jpg",
    name: "DailyWalks",
    id: generateRandomId(),
    site: "dailywalks.notnick.io",
    kind: "app",
    active: true,
    oss: false,
    desc: "A simple healthcare app to track your daily walks.",
  },
  {
    logo: "",
    name: "notnick.io",
    id: generateRandomId(),
    site: "notnick.io",
    kind: "website",
    link: "https://notnick.io",
    github: "https://github.com/alsonick/notnick.io",
    active: true,
    oss: true,
    desc: "You're currently on it right now! This is my own personal site.",
  },
  {
    logo: "",
    name: "Module Grade Calculator",
    id: generateRandomId(),
    site: "",
    link: "https://github.com/Nicholas-FnF/module-grade-calculator",
    github: "https://github.com/Nicholas-FnF/module-grade-calculator",
    kind: "website",
    active: true,
    oss: true,
    desc: "A small program to calculate module grades.",
  },
  {
    logo: "/project/branding/vercel-swag-logo.jpg",
    name: "vercel.notnick.io",
    id: generateRandomId(),
    site: "vercel.notnick.io",
    kind: "website",
    link: "https://vercel.notnick.io/",
    github: "https://github.com/alsonick/vercel.notnick.io",
    active: true,
    oss: true,
    desc: "A gallery collection site of vercel merchandise.",
  },
  {
    logo: "",
    name: "pics.notnick.io",
    id: generateRandomId(),
    site: "pics.notnick.io",
    kind: "website",
    link: "https://pics.notnick.io/",
    github: "https://github.com/alsonick/pics.notnick.io",
    active: true,
    oss: true,
    desc: "A personal photo gallery to showcase my pictures.",
  },
];
