import { generateRandomId } from "./generate-random-id";
import { Rag } from "../types/rag";

export const RAGS: Rag[] = [
  {
    id: generateRandomId(),
    composer: "Scott Joplin",
    title: "The Great Crush Collision March",
    score: "https://musescore.com/james_brigham/great-crush-collision-march",
    date: 1896,
    path: {
      composer: "joplin",
      file: "The Great Crush Collision March",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin",
    score: "https://musescore.com/user/58480/scores/238866",
    title: "Elite Syncopations",
    date: 1902,
    path: {
      composer: "joplin",
      file: "Elite Syncopations",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin",
    score: "https://musescore.com/user/58480/scores/1614131",
    title: "Euphonic Sounds",
    date: 1909,
    path: {
      composer: "joplin",
      file: "Euphonic Sounds",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin",
    score: "https://musescore.com/user/58480/scores/1750136",
    title: "The Favorite",
    date: 1904,
    path: {
      composer: "joplin",
      file: "The Favorite",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin & Scott Hayden",
    score: "https://musescore.com/user/58480/scores/1754361",
    title: "Felicity Rag",
    date: 1911,
    path: {
      composer: "joplin",
      file: "Felicity Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin",
    score: "https://musescore.com/user/58480/scores/1749906",
    title: "Gladiolus Rag",
    date: 1907,
    path: {
      composer: "joplin",
      file: "Gladiolus Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin",
    score: "https://musescore.com/user/58480/scores/2007551",
    title: "Harmony Club Waltz",
    date: 1896,
    path: {
      composer: "joplin",
      file: "Harmony Club Waltz",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin & Scott Hayden",
    score: "https://musescore.com/user/58480/scores/2786976",
    title: "Kismet Rag",
    date: 1913,
    path: {
      composer: "joplin",
      file: "Kismet Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin",
    score: "https://musescore.com/user/58480/scores/2582006",
    title: "Magnetic Rag",
    date: 1914,
    path: {
      composer: "joplin",
      file: "Magnetic Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin",
    score: "https://musescore.com/user/58480/scores/529121",
    title: "Maple Leaf Rag",
    date: 1899,
    path: {
      composer: "joplin",
      file: "Maple Leaf Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin",
    title: "The Nonpareil (None To Equal)",
    score: "https://musescore.com/user/58480/scores/1508466",
    date: 1907,
    path: {
      composer: "joplin",
      file: "The Nonpareil (None To Equal)",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin",
    score: "https://musescore.com/user/58480/scores/2011731",
    title: "Peacherine Rag",
    date: 1901,
    path: {
      composer: "joplin",
      file: "Peacherine Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin",
    score: "https://musescore.com/user/58480/scores/529116",
    title: "Stoptime Rag",
    date: 1910,
    path: {
      composer: "joplin",
      file: "Stoptime Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin",
    score: "https://musescore.com/james_brigham/scores/1581921",
    title: "Sugar Cane Rag",
    date: 1908,
    path: {
      composer: "joplin",
      file: "Sugar Cane Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin & Scott Hayden",
    score: "https://musescore.com/james_brigham/scores/2174986",
    title: "Sunflower Slow Drag",
    date: 1901,
    path: {
      composer: "joplin",
      file: "Sunflower Slow Drag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin",
    score: "https://musescore.com/user/10477211/scores/6289457",
    title: "The Ragtime Dance",
    date: 1906,
    path: {
      composer: "joplin",
      file: "The Ragtime Dance",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin",
    score: "https://musescore.com/james_brigham/fig-leaf-rag-scott-joplin-1908",
    title: "Fig Leaf Rag",
    date: 1908,
    path: {
      composer: "joplin",
      file: "Fig Leaf Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin",
    score: "https://musescore.com/james_brigham/the-cascades",
    title: "The Cascades",
    date: 1904,
    path: {
      composer: "joplin",
      file: "The Cascades",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Scott Joplin & Arthur Marshall",
    score: "https://musescore.com/crono23/lily-queen",
    title: "Lily Queen",
    date: 1907,
    path: {
      composer: "joplin",
      file: "Lily Queen",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Joseph Lamb",
    score: "https://musescore.com/user/36482158/scores/6563628",
    title: "Champagne Rag",
    date: 1910,
    path: {
      composer: "lamb",
      file: "Champagne Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Joseph Lamb",
    score: "https://musescore.com/user/36482158/scores/6561554",
    title: "Excelsior Rag",
    date: 1909,
    path: {
      composer: "lamb",
      file: "Excelsior Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Joseph Lamb",
    score: "https://musescore.com/piano_rags_lad/scores/6502245",
    title: "Reindeer Rag",
    date: 1915,
    path: {
      composer: "lamb",
      file: "Reindeer Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "Joseph Lamb",
    score: "https://musescore.com/piotrbarcz/scores/6420074",
    title: "Sensation Rag",
    date: 1908,
    path: {
      composer: "lamb",
      file: "Sensation Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "James Scott",
    score: "https://musescore.com/user/36482158/scores/10770310",
    title: "Efficiency Rag",
    date: 1917,
    path: {
      composer: "scott",
      file: "Efficiency Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "James Scott",
    score: "https://musescore.com/user/36482158/scores/6524265",
    title: "Frog Legs Rag",
    date: 1906,
    path: {
      composer: "scott",
      file: "Frog Legs Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "James Scott",
    score: "https://musescore.com/user/36482158/scores/9142581",
    title: "Hilarity Rag",
    date: 1910,
    path: {
      composer: "scott",
      file: "Hilarity Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "James Scott",
    score: "https://musescore.com/user/36482158/scores/10760014",
    title: "Honey Moon Rag",
    date: 1916,
    path: {
      composer: "scott",
      file: "Honey Moon Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "James Scott",
    score: "https://musescore.com/user/36482158/scores/6524362",
    title: "Ragtime Oriole",
    date: 1911,
    path: {
      composer: "scott",
      file: "Ragtime Oriole",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "James Scott",
    score: "https://musescore.com/user/33456843/scores/6535412",
    title: "Victory Rag",
    date: 1921,
    path: {
      composer: "scott",
      file: "Victory Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "James Scott",
    score: "https://musescore.com/user/3224/scores/2277741",
    title: "Climax Rag",
    date: 1914,
    path: {
      composer: "scott",
      file: "Climax Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "James Scott",
    score: "https://musescore.com/user/58480/scores/5101474",
    title: "Evergreen Rag",
    date: 1915,
    path: {
      composer: "scott",
      file: "Evergreen Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "James Scott",
    score: "https://musescore.com/user/36482158/scores/15064630",
    title: "Peace and Plenty Rag",
    date: 1919,
    path: {
      composer: "scott",
      file: "Peace And Plenty Rag",
      ext: "mp3",
    },
  },
  {
    id: generateRandomId(),
    composer: "L. Edgar Settle",
    score: "https://musescore.com/user/13824426/scores/4732786",
    title: "X. L. Rag",
    date: 1903,
    path: {
      composer: "settle",
      file: "X. L. Rag",
      ext: "mp3",
    },
  },
];
