export const SOCIALS = [
  {
    id: 1,
    title: "Twitter",
    username: "@heynickn",
    type: "Thoughts",
    link: "https://twitter.com/heynickn",
  },
  {
    id: 2,
    title: "Instagram",
    username: "heynickn",
    type: "Life",
    link: "https://www.instagram.com/heynickn/",
  },
  {
    id: 3,
    title: "Snapchat",
    username: "notnick14",
    type: "Fun",
    link: "https://www.snapchat.com/add/notnick14",
  },
  {
    id: 4,
    title: "LinkedIn",
    username: "nicholas-n-5a9187195",
    type: "Professional",
    link: "https://www.linkedin.com/in/nicholas-n-5a9187195/",
  },
  {
    id: 5,
    title: "Reddit",
    username: "thisnotnicholas",
    type: "Info",
    link: "https://www.reddit.com/user/thisnotnicholas",
  },
  {
    id: 6,
    title: "Twitch",
    username: "alsonick_",
    type: "Streaming",
    link: "https://www.twitch.tv/alsonick_",
  },
  {
    id: 7,
    title: "Discord",
    username: "Nicholas#0050",
    type: "Talk",
    link: "",
  },
];
