export const technologies = [
  {
    id: 1,
    text: "React.js",
    link: "https://reactjs.org/",
    desc: "A JavaScript library for building user interfaces.",
  },
  {
    id: 2,
    text: "TypeScript",
    link: "https://www.typescriptlang.org/",
    desc: "A strongly typed programming language that builds on JavaScript, giving you better tooling at any scale.",
  },
  {
    id: 3,
    text: "styled-components",
    link: "https://styled-components.com/",
    desc: "A library for React and React Native that allows you to use component-level styles in your application.",
  },
  {
    id: 4,
    text: "TailwindCSS",
    link: "https://tailwindcss.com/",
    desc: "An open source CSS framework.",
  },
  {
    id: 5,
    text: "Prisma",
    link: "https://www.prisma.io/",
    desc: "An open-source ORM for Node. js and TypeScript.",
  },
  {
    id: 6,
    text: "Git",
    link: "https://git-scm.com/",
    desc: "An open source software for distributed version control.",
  },
  {
    id: 7,
    text: "Visual Studio Code",
    link: "https://code.visualstudio.com/",
    desc: "An a source-code editor made by Microsoft for Windows, Linux and macOS.",
  },
  {
    id: 8,
    text: "Node.js",
    link: "https://nodejs.org/en/",
    desc: "A JavaScript runtime environment built on top of the v8 engine.",
  },
  {
    id: 9,
    text: "Next.js",
    link: "https://nextjs.org/",
    desc: "A React framework that gives you building blocks to create web applications.",
  },
  {
    id: 10,
    text: "Docker",
    link: "https://www.docker.com/",
    desc: "An open platform for developing, shipping, and running applications. Docker enables you to separate your applications from your infrastructure so you can deliver software quickly.",
  },
  {
    id: 11,
    text: "Postgres",
    link: "https://www.postgresql.org/",
    desc: "An open source object-relational database system that uses and extends the SQL language.",
  },
  {
    id: 12,
    text: "Yarn",
    link: "https://yarnpkg.com/",
    desc: "A package manager developed by Facebook for the Node.js JavaScript runtime environment.",
  },
  {
    id: 13,
    text: "npm",
    link: "https://www.npmjs.com/",
    desc: "A package manager for the JavaScript programming language.",
  },
  {
    id: 14,
    text: "Express",
    link: "https://expressjs.com/",
    desc: "A framework that runs within Node.js that allows developers to create backend services.",
  },
  {
    id: 15,
    text: "Fastify",
    link: "https://www.fastify.io/",
    desc: "A framework that allows developers to create backend services.",
  },
  {
    id: 16,
    text: "JavaScript",
    link: "https://www.ecma-international.org/publications-and-standards/standards/ecma-262/",
    desc: "A programming language for the web.",
  },
  {
    id: 17,
    text: "Rust",
    link: "https://www.rust-lang.org/",
    desc: "A statically-typed programming language designed for performance and safety.",
  },
];
